version: '3.0'
services:
  rasa:
    image: rasa/rasa:1.10.8-full
    ports:
      - 5005:5005
    volumes:
      - ./models:/app/models
      - ./config:/app/config
    command:
      - rasa
      - run
      - -- cors
      - "*"
